In [210]:
import pandas as pd
import numpy as np

In [211]:
pd.set_option('display.max_columns', 500)

In [212]:
df=pd.read_csv('marketing_sample_for_naukri_com-jobs__20190701_20190830__30k_data.csv')
df.head()

,Uniq Id,Crawl Timestamp,Job Title,Job Salary,Job Experience Required,Key Skills,Role Category,Location,Functional Area,Industry,Role
0,9be62c49a0b7ebe982a4af1edaa7bc5f,2019-07-05 01:46:07 +0000,Digital Media Planner,Not Disclosed by Recruiter,5 - 10 yrs,Media Planning| Digital Media,Advertising,Mumbai,"Marketing , Advertising , MR , PR , Media Plan...","Advertising, PR, MR, Event Management",Media Planning Executive/Manager
1,3c52d436e39f596b22519da2612f6a56,2019-07-06 08:04:50 +0000,Online Bidding Executive,Not Disclosed by Recruiter,2 - 5 yrs,pre sales| closing| software knowledge| clien...,Retail Sales,"Pune,Pune","Sales , Retail , Business Development","IT-Software, Software Services",Sales Executive/Officer
2,ffad8a2396c60be2bf6d0e2ff47c58d4,2019-08-05 15:50:44 +0000,Trainee Research/ Research Executive- Hi- Tec...,Not Disclosed by Recruiter,0 - 1 yrs,Computer science| Fabrication| Quality check|...,R&D,Gurgaon,"Engineering Design , R&D","Recruitment, Staffing",R&D Executive
3,7b921f51b5c2fb862b4a5f7a54c37f75,2019-08-05 15:31:56 +0000,Technical Support,"2,00,000 - 4,00,000 PA.",0 - 5 yrs,Technical Support,Admin/Maintenance/Security/Datawarehousing,Mumbai,"IT Software - Application Programming , Mainte...","IT-Software, Software Services",Technical Support Engineer
4,2d8b7d44e138a54d5dc841163138de50,2019-07-05 02:48:29 +0000,Software Test Engineer -hyderabad,Not Disclosed by Recruiter,2 - 5 yrs,manual testing| test engineering| test cases|...,Programming & Design,Hyderabad,IT Software - QA & Testing,"IT-Software, Software Services",Testing Engineer

In [213]:
df['Job Title']=df['Job Title'].fillna('').map(lambda x:x.strip().lower())

In [214]:
df.columns

Index(['Uniq Id', 'Crawl Timestamp', 'Job Title', 'Job Salary',
       'Job Experience Required', 'Key Skills', 'Role Category', 'Location',
       'Functional Area', 'Industry', 'Role'],
      dtype='object')

In [215]:
len(df['Job Title'].unique())

23230

In [216]:
df.shape

(30000, 11)

In [217]:
df.isnull().sum()

Uniq Id                       0
Crawl Timestamp               0
Job Title                     0
Job Salary                   50
Job Experience Required     573
Key Skills                 1271
Role Category              2305
Location                    577
Functional Area             573
Industry                    573
Role                        901
dtype: int64

In [218]:
df['Key Skills'].fillna('Not given',inplace=True)

In [219]:
df['Skill_1']=df['Key Skills'].map(lambda x:x.split('|')[0].lower().strip() if x!='Not given' else "Not Given")

In [220]:
df['Skill_1']

0           media planning
1                pre sales
2         computer science
3        technical support
4           manual testing
               ...
29995             graphics
29996     service delivery
29997            counselor
29998    security analysis
29999        press release
Name: Skill_1, Length: 30000, dtype: object

In [221]:
len(df['Skill_1'].unique())

5096

In [222]:
df['Skill_2']=df['Key Skills'].map(lambda x:x.split('|')[1].lower().strip() if x!='Not given' and len(x.split('|'))>1 else "Not Given")

In [223]:
len(df['Skill_2'].unique())

5378

In [224]:
df['Skill_3']=df['Key Skills'].map(lambda x:x.split('|')[2].lower().strip() if x!='Not given' and len(x.split('|'))>2 else "Not Given")

In [225]:
df.head()

,Uniq Id,Crawl Timestamp,Job Title,Job Salary,Job Experience Required,Key Skills,Role Category,Location,Functional Area,Industry,Role,Skill_1,Skill_2,Skill_3
0,9be62c49a0b7ebe982a4af1edaa7bc5f,2019-07-05 01:46:07 +0000,digital media planner,Not Disclosed by Recruiter,5 - 10 yrs,Media Planning| Digital Media,Advertising,Mumbai,"Marketing , Advertising , MR , PR , Media Plan...","Advertising, PR, MR, Event Management",Media Planning Executive/Manager,media planning,digital media,Not Given
1,3c52d436e39f596b22519da2612f6a56,2019-07-06 08:04:50 +0000,online bidding executive,Not Disclosed by Recruiter,2 - 5 yrs,pre sales| closing| software knowledge| clien...,Retail Sales,"Pune,Pune","Sales , Retail , Business Development","IT-Software, Software Services",Sales Executive/Officer,pre sales,closing,software knowledge
2,ffad8a2396c60be2bf6d0e2ff47c58d4,2019-08-05 15:50:44 +0000,trainee research/ research executive- hi- tech...,Not Disclosed by Recruiter,0 - 1 yrs,Computer science| Fabrication| Quality check|...,R&D,Gurgaon,"Engineering Design , R&D","Recruitment, Staffing",R&D Executive,computer science,fabrication,quality check
3,7b921f51b5c2fb862b4a5f7a54c37f75,2019-08-05 15:31:56 +0000,technical support,"2,00,000 - 4,00,000 PA.",0 - 5 yrs,Technical Support,Admin/Maintenance/Security/Datawarehousing,Mumbai,"IT Software - Application Programming , Mainte...","IT-Software, Software Services",Technical Support Engineer,technical support,Not Given,Not Given
4,2d8b7d44e138a54d5dc841163138de50,2019-07-05 02:48:29 +0000,software test engineer -hyderabad,Not Disclosed by Recruiter,2 - 5 yrs,manual testing| test engineering| test cases|...,Programming & Design,Hyderabad,IT Software - QA & Testing,"IT-Software, Software Services",Testing Engineer,manual testing,test engineering,test cases

In [226]:
df['Role Category'].fillna('Not Given',inplace=True)

In [227]:
df['Role Category']=df['Role Category'].map(lambda x:x.split('/')[0].lower().strip() if '/' in x else x.lower())

In [228]:
role_dict=df['Role Category'].value_counts().to_dict()

In [229]:
final_role_dict={k:i for k,i in role_dict.items() if i>=6}

In [230]:
roles_keys=final_role_dict.keys()

In [231]:
df['Role Category']=df['Role Category'].map(lambda x:x if x in roles_keys else "Other")

In [232]:
df['Role Category'].value_counts().to_dict()

{'programming & design': 8551,
 'voice': 2385,
 'retail sales': 2359,
 'not given': 2305,
 'hr': 1133,
 'admin': 928,
 'accounts': 882,
 'senior management': 880,
 'other': 865,
 'corporate sales': 704,
 'production': 643,
 'system design': 507,
 'marketing': 487,
 'medical professional': 438,
 'creative': 396,
 'engineering design': 368,
 'finance': 339,
 'teachers': 329,
 'project management': 311,
 'university level': 305,
 'back office': 294,
 'institutional sales': 285,
 'operations': 264,
 'site engineering': 250,
 'retail': 248,
 'channel sales': 245,
 'analytics & bi': 215,
 'r&d': 208,
 'content development': 206,
 'purchase': 169,
 'Other': 160,
 'food & beverage': 146,
 'sales support': 142,
 'administration': 142,
 'logistics': 138,
 'advertising': 129,
 'online': 121,
 'corporate planning': 118,
 'qa': 110,
 'ticketing': 108,
 'technical support': 95,
 'life insurance': 85,
 'quality': 63,
 'architectural services': 62,
 'corporate banking': 62,
 'it hardware': 56,
 'designer': 52,
 'financial services': 49,
 'front office': 48,
 'drug regulatory affairs': 46,
 'marketing research': 45,
 'investment banking': 43,
 'documentation': 41,
 'training': 39,
 'interior design': 37,
 'mutual funds': 30,
 'journalist': 28,
 'safety': 28,
 'pre sales': 27,
 'treasury': 25,
 'public relations': 24,
 'general insurance': 23,
 'housekeeping': 21,
 'after sales service': 20,
 'subject teachers (tgt': 19,
 'telecom': 17,
 'shipping': 16,
 'life skills': 15,
 'editor': 15,
 'health & fitness': 11,
 'airline': 11,
 'language teachers (tgt': 11,
 'card products': 10,
 'quality assurance & quality control-compliance & regulatory': 7,
 'beauty services': 6}

In [233]:
df['Job Experience Required'].value_counts().to_dict()

{'2 - 5 yrs': 2002,
 '2 - 7 yrs': 1659,
 '5 - 10 yrs': 1510,
 '3 - 8 yrs': 1366,
 '1 - 3 yrs': 1189,
 '3 - 5 yrs': 1063,
 '1 - 6 yrs': 1032,
 '1 - 5 yrs': 977,
 '0 - 5 yrs': 933,
 '0 - 1 yrs': 855,
 '0 - 2 yrs': 852,
 '2 - 4 yrs': 828,
 '4 - 9 yrs': 807,
 '0 - 3 yrs': 774,
 '3 - 6 yrs': 764,
 '2 - 6 yrs': 731,
 '5 - 8 yrs': 643,
 '1 - 4 yrs': 617,
 '1 - 2 yrs': 583,
 '4 - 8 yrs': 560,
 '4 - 6 yrs': 492,
 '2 - 3 yrs': 461,
 '10 - 15 yrs': 438,
 '3 - 7 yrs': 416,
 '7 - 12 yrs': 395,
 '8 - 13 yrs': 380,
 '6 - 11 yrs': 355,
 '5 - 7 yrs': 318,
 '4 - 7 yrs': 313,
 '7 - 10 yrs': 280,
 '0 - 4 yrs': 275,
 '6 - 10 yrs': 272,
 '8 - 10 yrs': 262,
 '0 - 0 yrs': 258,
 '8 - 12 yrs': 235,
 '6 - 8 yrs': 221,
 '3 - 4 yrs': 192,
 '10 - 20 yrs': 190,
 '5 - 9 yrs': 175,
 'Not Mentioned': 173,
 '10 - 12 yrs': 167,
 '4 - 5 yrs': 155,
 '15 - 20 yrs': 116,
 '9 - 14 yrs': 116,
 '6 - 9 yrs': 107,
 ' 3 - 8 Years': 97,
 ' 2 - 5 Years': 90,
 '10 - 14 yrs': 84,
 '5 - 6 yrs': 84,
 ' 5 - 10 Years': 84,
 '12 - 15 yrs': 79,
 '15 - 18 yrs': 75,
 ' 4 - 9 Years': 64,
 ' 3 - 5 Years': 62,
 '15 - 25 yrs': 60,
 ' 1 - 5 Years': 59,
 ' 1 - 3 Years': 55,
 ' 1 - 6 Years': 54,
 ' 3 - 6 Years': 49,
 ' 5 - 8 Years': 48,
 ' 4 - 6 Years': 46,
 ' 0 - 5 Years': 45,
 ' 2 - 7 Years': 45,
 '7 - 9 yrs': 45,
 ' 4 - 8 Years': 44,
 ' 7 - 12 Years': 42,
 ' 2 - 6 Years': 41,
 '7 - 11 yrs': 38,
 '9 - 12 yrs': 38,
 ' 2 - 4 Years': 38,
 ' 8 - 13 Years': 37,
 ' 0 - 1 Years': 36,
 '12 - 16 yrs': 36,
 ' 0 - 2 Years': 35,
 '12 - 17 yrs': 35,
 '10 - 13 yrs': 35,
 '12 - 20 yrs': 34,
 ' 3 - 7 Years': 32,
 ' 1 - 4 Years': 32,
 '12 - 18 yrs': 31,
 '10 - 16 yrs': 30,
 '10 - 18 yrs': 29,
 ' 0 - 3 Years': 29,
 ' 5 - 7 Years': 29,
 '8 - 11 yrs': 28,
 '6 - 7 yrs': 27,
 ' 10 - 15 Years': 26,
 ' 8 - 12 Years': 25,
 '7 - 8 yrs': 25,
 '12 - 22 yrs': 24,
 ' 6 - 11 Years': 24,
 ' 8 - 10 Years': 24,
 ' 6 - 10 Years': 23,
 '9 - 13 yrs': 22,
 ' 0 Years': 21,
 ' 0 - 4 Years': 20,
 ' 4 - 7 Years': 20,
 ' 6 - 8 Years': 19,
 '10 - 17 yrs': 19,
 ' 7 - 10 Years': 18,
 ' 10 - 12 Years': 18,
 '11 - 15 yrs': 17,
 ' 5 - 6 Years': 16,
 ' 5 - 9 Years': 15,
 ' 6 - 9 Years': 15,
 ' 9 - 14 Years': 13,
 ' 2 - 3 Years': 13,
 ' 1 - 2 Years': 13,
 '12 - 14 yrs': 13,
 ' 3 - 4 Years': 13,
 '13 - 18 yrs': 12,
 '13 - 17 yrs': 11,
 '20 - 25 yrs': 11,
 ' 4 - 5 Years': 11,
 '20 - 30 yrs': 10,
 '15 - 19 yrs': 10,
 ' 10 - 20 Years': 10,
 '2 - 8 yrs': 10,
 '14 - 20 yrs': 9,
 '15 - 17 yrs': 9,
 '2 - 2 yrs': 9,
 '11 - 21 yrs': 9,
 '16 - 20 yrs': 8,
 '15 - 22 yrs': 8,
 '11 - 14 yrs': 8,
 '18 - 25 yrs': 8,
 '14 - 24 yrs': 7,
 ' 9 - 12 Years': 7,
 '10 - 19 yrs': 7,
 '9 - 10 yrs': 7,
 '1 - 1 yrs': 7,
 '13 - 15 yrs': 6,
 '18 - 20 yrs': 6,
 '14 - 18 yrs': 6,
 ' 7 - 9 Years': 6,
 ' 7 - 8 Years': 6,
 '18 - 22 yrs': 6,
 ' 10 - 17 Years': 6,
 ' 7 - 11 Years': 6,
 '11 - 16 yrs': 6,
 '9 - 11 yrs': 6,
 ' 12 - 15 Years': 5,
 ' 12 - 20 Years': 5,
 '14 - 16 yrs': 5,
 '0 - 8 yrs': 5,
 '8 - 9 yrs': 4,
 ' 10 - 14 Years': 4,
 '14 - 17 yrs': 4,
 ' 10 - 13 Years': 4,
 '20 - 26 yrs': 4,
 ' 12 - 18 Years': 4,
 ' 10 - 18 Years': 4,
 '15 - 23 yrs': 4,
 '16 - 18 yrs': 4,
 ' 12 - 16 Years': 4,
 '13 - 20 yrs': 4,
 '14 - 22 yrs': 4,
 '15 - 16 yrs': 3,
 '14 - 15 yrs': 3,
 ' 14 - 20 Years': 3,
 '14 - 19 yrs': 3,
 '15 - 24 yrs': 3,
 '12 - 19 yrs': 3,
 '13 - 21 yrs': 3,
 ' 15 - 20 Years': 3,
 '25 - 30 yrs': 3,
 ' 12 - 22 Years': 3,
 '11 - 13 yrs': 3,
 '12 - 13 yrs': 3,
 '11 - 20 yrs': 3,
 '13 - 16 yrs': 3,
 ' 10 - 16 Years': 3,
 '10 - 11 yrs': 3,
 '1 - 7 yrs': 3,
 '16 - 25 yrs': 3,
 '17 - 25 yrs': 3,
 ' 8 - 11 Years': 3,
 '1 - 10 yrs': 2,
 '0 - 10 yrs': 2,
 '16 - 26 yrs': 2,
 ' 14 - 24 Years': 2,
 ' 8 - 9 Years': 2,
 '13 - 23 yrs': 2,
 '11 - 12 yrs': 2,
 '16 - 22 yrs': 2,
 '0 - 7 yrs': 2,
 '3 - 10 yrs': 2,
 '15 - 21 yrs': 2,
 ' 13 - 15 Years': 2,
 '3 - 3 yrs': 2,
 '20 - 24 yrs': 2,
 ' 9 - 10 Years': 2,
 '20 - 22 yrs': 2,
 '5 - 15 yrs': 2,
 '12 - 21 yrs': 2,
 '2 - 10 yrs': 2,
 '1 - 8 yrs': 2,
 ' 10 - 11 Years': 2,
 '4 - 10 yrs': 2,
 ' 13 - 20 Years': 2,
 '11 - 18 yrs': 2,
 ' 15 - 17 Years': 2,
 '18 - 28 yrs': 2,
 '5 - 5 yrs': 2,
 ' 9 - 13 Years': 2,
 '23 - 25 yrs': 1,
 ' 14 - 22 Years': 1,
 ' 14 - 16 Years': 1,
 '16 - 21 yrs': 1,
 '8 - 15 yrs': 1,
 '25 - 25 yrs': 1,
 '0 - 22 yrs': 1,
 '20 - 23 yrs': 1,
 '16 - 23 yrs': 1,
 '7 - 7 yrs': 1,
 '3 - 12 yrs': 1,
 '18 - 27 yrs': 1,
 '6 - 12 yrs': 1,
 '22 - 30 yrs': 1,
 ' 19 - 29 Years': 1,
 ' 15 - 18 Years': 1,
 '0 - 15 yrs': 1,
 ' 12 - 17 Years': 1,
 ' 11 - 17 Years': 1,
 ' 13 - 17 Years': 1,
 ' 19 - 28 Years': 1,
 '7 - 15 yrs': 1,
 '13 - 19 yrs': 1,
 '0 - 9 yrs': 1,
 '2 - 9 yrs': 1,
 ' 13 - 16 Years': 1,
 '9 - 15 yrs': 1,
 ' 11 - 20 Years': 1,
 '17 - 18 yrs': 1,
 '17 - 27 yrs': 1,
 ' 19 - 25 Years': 1,
 ' 12 - 19 Years': 1,
 '22 - 24 yrs': 1,
 ' 30 years and above': 1,
 '11 - 17 yrs': 1,
 '5 - 11 yrs': 1,
 '25 - 31 yrs': 1,
 '16 - 24 yrs': 1,
 '0 - 6 yrs': 1,
 '14 - 21 yrs': 1,
 '30 years and above': 1,
 ' 11 - 12 Years': 1,
 ' 19 - 24 Years': 1,
 ' 14 - 18 Years': 1,
 ' 18 - 25 Years': 1,
 ' 15 - 22 Years': 1,
 ' 12 - 14 Years': 1,
 '17 - 21 yrs': 1,
 '2 - 12 yrs': 1,
 ' 12 - 13 Years': 1,
 '25 - 35 yrs': 1}

In [234]:
df['Job Experience Required'].fillna("Not Mentioned",inplace=True)

In [235]:
df['Job_Exp_Min']=df['Job Experience Required'].map(lambda x:x.split(' - ')[0].strip() if x not in ['Not Mentioned','30 years and above'] else "Other")

In [236]:
df['Job_Exp_Min']

0        5
1        2
2        0
3        0
4        2
        ..
29995    9
29996    1
29997    4
29998    5
29999    2
Name: Job_Exp_Min, Length: 30000, dtype: object

In [237]:
df['Job_Exp_Max']=df['Job Experience Required'].map(lambda x:x.split(' - ')[1][:2].strip() if x not in ['Not Mentioned','30 years and above'] and '-' in x else "Other")

In [238]:
df['Job_Exp_Max']

0        10
1         5
2         1
3         5
4         5
         ..
29995    12
29996     5
29997     6
29998    10
29999     7
Name: Job_Exp_Max, Length: 30000, dtype: object

In [239]:
df['Industry'].fillna("Not Given",inplace=True)

In [240]:
df['Industry']=df['Industry'].map(lambda x:x.split(',')[0].lower().strip())

In [241]:
df['Industry']=df['Industry'].map(lambda x:x.split(' / ')[0].lower().strip() if ' / ' in x else x )

In [242]:
industry_dict=df['Industry'].value_counts().to_dict()

In [243]:
industry_dict={k:v for k,v in industry_dict.items() if v>=3}

In [244]:
industry_keys=industry_dict.keys()

In [245]:
df['Industry']=df['Industry'].map(lambda x:x if x in industry_keys else "other")

In [246]:
df.head(10)

,Uniq Id,Crawl Timestamp,Job Title,Job Salary,Job Experience Required,Key Skills,Role Category,Location,Functional Area,Industry,Role,Skill_1,Skill_2,Skill_3,Job_Exp_Min,Job_Exp_Max
0,9be62c49a0b7ebe982a4af1edaa7bc5f,2019-07-05 01:46:07 +0000,digital media planner,Not Disclosed by Recruiter,5 - 10 yrs,Media Planning| Digital Media,advertising,Mumbai,"Marketing , Advertising , MR , PR , Media Plan...",advertising,Media Planning Executive/Manager,media planning,digital media,Not Given,5,10
1,3c52d436e39f596b22519da2612f6a56,2019-07-06 08:04:50 +0000,online bidding executive,Not Disclosed by Recruiter,2 - 5 yrs,pre sales| closing| software knowledge| clien...,retail sales,"Pune,Pune","Sales , Retail , Business Development",it-software,Sales Executive/Officer,pre sales,closing,software knowledge,2,5
2,ffad8a2396c60be2bf6d0e2ff47c58d4,2019-08-05 15:50:44 +0000,trainee research/ research executive- hi- tech...,Not Disclosed by Recruiter,0 - 1 yrs,Computer science| Fabrication| Quality check|...,r&d,Gurgaon,"Engineering Design , R&D",recruitment,R&D Executive,computer science,fabrication,quality check,0,1
3,7b921f51b5c2fb862b4a5f7a54c37f75,2019-08-05 15:31:56 +0000,technical support,"2,00,000 - 4,00,000 PA.",0 - 5 yrs,Technical Support,admin,Mumbai,"IT Software - Application Programming , Mainte...",it-software,Technical Support Engineer,technical support,Not Given,Not Given,0,5
4,2d8b7d44e138a54d5dc841163138de50,2019-07-05 02:48:29 +0000,software test engineer -hyderabad,Not Disclosed by Recruiter,2 - 5 yrs,manual testing| test engineering| test cases|...,programming & design,Hyderabad,IT Software - QA & Testing,it-software,Testing Engineer,manual testing,test engineering,test cases,2,5
5,c9628ea8d9cfd2ca72e14d53783aca90,2019-08-05 03:59:27 +0000,opening for adobe analytics specialist,"7,00,000 - 17,00,000 PA.",5 - 7 yrs,adobe experience manager| digital| digital ma...,programming & design,Pune,"IT Software - Application Programming , Mainte...",it-software,System Analyst,adobe experience manager,digital,digital marketing,5,7
6,2008eb365fa0ebcb1ccd9a50efc3da49,2019-07-06 09:20:22 +0000,sales- fresher-for leading property consultant,"2,00,000 - 3,00,000 PA.",0 - 0 yrs,channel partners| real estate| negotiation| p...,retail sales,Bengaluru,"Sales , Retail , Business Development",real estate,Sales Executive/Officer,channel partners,real estate,negotiation,0,0
7,9642bed00e26183e41ab73778bf48108,2019-08-04 03:31:17 +0000,opportunity for azure devops architect for hyd...,Not Disclosed by Recruiter,9 - 14 yrs,TFS| Azure| Git| VSTS| Docker| DynaTrace| Spl...,programming & design,Hyderabad,"IT Software - Application Programming , Mainte...",it-software,Technical Architect,tfs,azure,git,9,14
8,2633768efe8c6f72d75158f1c173f893,2019-07-06 15:41:47 +0000,bde- pune,Not Disclosed by Recruiter,2 - 7 yrs,Bde,institutional sales,Pune,"Sales , Retail , Business Development",it-software,Sales Executive/Officer,bde,Not Given,Not Given,2,7
9,138a9ab97a766d8048f5b246172f65ed,2019-07-04 12:37:52 +0000,technical support/ product support,Not Disclosed by Recruiter,1 - 5 yrs,technical support| support services| applicat...,voice,Bengaluru,"ITES , BPO , KPO , LPO , Customer Service , Op...",it-software,Associate/Senior Associate -(Technical),technical support,support services,application support,1,5

In [247]:
df['Location']=df['Location'].fillna("Not Given").map(lambda x:x.lower().strip())

In [248]:
df['Location'].value_counts().to_dict()

{'bengaluru': 5215,
 'mumbai': 3393,
 'pune': 2512,
 'hyderabad': 2281,
 'gurgaon': 1787,
 'chennai': 1613,
 'kolkata': 1361,
 'delhi': 1223,
 'noida': 1180,
 'ahmedabad': 1040,
 'delhi ncr': 768,
 'not given': 577,
 'chandigarh': 310,
 'navi mumbai': 172,
 'delhi ncr,gurgaon': 141,
 'faridabad': 121,
 'delhi ncr,gurgaon,noida': 113,
 'mumbai,mumbai suburbs': 93,
 'ghaziabad': 84,
 'mumbai,mumbai suburbs,navi mumbai': 82,
 'bengaluru,hyderabad': 78,
 'mumbai,pune': 77,
 'delhi ncr,noida': 74,
 'mumbai,mumbai': 70,
 'greater noida': 68,
 'bengaluru,chennai': 65,
 'mumbai,navi mumbai': 64,
 'thane': 62,
 'gurgaon,haryana': 59,
 'mumbai suburbs': 58,
 'bengaluru,chennai,hyderabad': 47,
 'gurgaon,noida': 46,
 'delhi ncr,delhi': 46,
 'gurgaon,delhi': 44,
 'bengaluru,bengaluru / bangalore': 44,
 'delhi,gurgaon': 44,
 'mumbai,bengaluru': 41,
 'chennai,chennai': 39,
 'mumbai,navi mumbai,thane': 38,
 'bengaluru,pune': 37,
 'delhi ncr,mumbai,bengaluru': 34,
 'mumbai,thane': 34,
 'delhi,delhi': 34,
 'hyderabad,hyderabad/secunderabad': 32,
 'bengaluru,mumbai': 32,
 'hyderabad,bengaluru': 31,
 'gurgaon,gurgaon': 29,
 'noida,noida/greater noida': 29,
 'navi mumbai,mumbai': 27,
 'bengaluru,gurgaon': 27,
 'noida,delhi': 26,
 'mumbai,delhi': 25,
 'chennai,coimbatore': 24,
 'delhi ncr,delhi,gurgaon': 24,
 'noida,greater noida': 24,
 'chennai,hyderabad': 23,
 'bengaluru,bangalore east': 23,
 'chandigarh,mohali': 22,
 'hyderabad,hyderabad': 21,
 'bengaluru,delhi': 20,
 'bengaluru (whitefield)': 20,
 'hyderabad (madhapur)': 19,
 'bengaluru,bangalore': 18,
 'delhi ncr,bengaluru': 18,
 'pune,pune': 17,
 'hyderabad (gachibowli)': 17,
 'kolkata,kolkata': 17,
 'noida (sector-62 noida)': 16,
 'delhi,delhi ncr': 16,
 'gurgaon (udyog vihar)': 16,
 'delhi ncr,mumbai': 16,
 'mumbai,chennai': 16,
 'gurgaon,delhi ncr': 16,
 'gurgaon,ghaziabad': 16,
 'chennai,hyderabad,pune': 16,
 'bengaluru,noida': 16,
 'delhi ncr,faridabad,gurgaon': 15,
 'ahmedabad,ahmedabad': 15,
 'mumbai,mumbai suburbs,thane': 15,
 'mumbai,navi mumbai,mumbai suburbs': 14,
 'pune (baner)': 14,
 'hyderabad,pune': 14,
 'mumbai,hyderabad': 14,
 'gurgaon (cyber city)': 14,
 'chennai,bengaluru': 14,
 'pune (viman nagar)': 13,
 'bengaluru,india': 13,
 'mumbai (marol)': 13,
 'gurgaon,chandigarh,haryana': 13,
 'mumbai,bengaluru,pune': 13,
 'mohali,chandigarh': 12,
 'bengaluru,hyderabad,chennai': 12,
 'bengaluru,kolkata': 12,
 'greater noida,noida': 12,
 'gurgaon,bengaluru': 12,
 'ahmedabad,vadodara': 11,
 'anand,thane': 11,
 'gurgaon (sohna road)': 11,
 'gurgaon,mumbai': 11,
 'noida (sector-63 noida)': 11,
 'mumbai,bengaluru,hyderabad': 11,
 'noida,gurgaon': 11,
 'mumbai,bengaluru,delhi': 10,
 'pune,mumbai': 10,
 'ahmedabad,gujarat': 10,
 'delhi ncr,greater noida,noida': 10,
 'pune,hyderabad': 10,
 'pune (kalyani nagar)': 10,
 'delhi,mumbai': 10,
 'delhi ncr,noida,gurgaon': 10,
 'gurgaon,gurugram': 10,
 'chennai,pune': 9,
 'chandigarh,chandigarh': 9,
 'gurgaon,delhi,noida': 9,
 'hyderabad,chennai': 9,
 'chennai,mumbai': 9,
 'bengaluru,mysore': 9,
 'delhi ncr,delhi,noida': 9,
 'bengaluru (indira nagar)': 9,
 'ahmedabad,mumbai': 9,
 'mumbai,pune,ahmedabad': 9,
 'noida,lucknow': 9,
 'pune,ahmedabad': 9,
 'bengaluru,hyderabad,pune': 9,
 'delhi ncr (okhla)': 8,
 'bengaluru,hosur': 8,
 'mumbai,bengaluru,chennai': 8,
 'delhi ncr,pune': 8,
 'ahmedabad,gandhinagar': 8,
 'pune (chakan)': 8,
 'delhi ncr,faridabad,noida': 8,
 'mumbai (powai)': 8,
 'delhi,gurgaon,noida': 8,
 'chennai,delhi': 8,
 'mumbai,pune,navi mumbai': 8,
 'mumbai (vikhroli)': 8,
 'delhi,noida': 8,
 'pune,gurgaon': 8,
 'delhi ncr,bengaluru,hyderabad': 7,
 'hyderabad,bengaluru,chennai': 7,
 'bengaluru,kochi': 7,
 'mumbai suburbs,mumbai': 7,
 'mumbai,kolkata': 7,
 'pune,bengaluru': 7,
 'ghaziabad,ghaziabad': 7,
 'ahmedabad,surat,vadodara': 7,
 'hyderabad,bengaluru,pune': 7,
 'mumbai,ahmedabad': 7,
 'mumbai,mumbai suburbs,navi mumbai,thane': 7,
 'ahmedabad (prahlad nagar)': 7,
 'hyderabad, vapi': 7,
 'delhi ncr,bengaluru,chennai': 7,
 'noida (sector-60 noida)': 7,
 'howrah,howrah': 7,
 'bengaluru,mumbai,delhi': 7,
 'hyderabad,mumbai': 7,
 'delhi ncr,ghaziabad,gurgaon': 7,
 'mumbai (lower parel)': 7,
 'gurgaon,pune': 6,
 'bengaluru,chennai,pune': 6,
 'gurgaon,manesar': 6,
 'pune (shivaji nagar)': 6,
 'hyderabad,visakhapatnam': 6,
 'delhi ncr,mumbai,bengaluru,chennai,hyderabad,pune,kolkata,ahmedabad,trivandrum': 6,
 'delhi (netaji subhash place)': 6,
 'bengaluru (koramangala)': 6,
 'kolkata (salt lake)': 6,
 'hyderabad,ahmedabad': 6,
 'bengaluru,delhi ncr': 6,
 'noida,delhi ncr': 6,
 'chandigarh,punjab': 6,
 'hyderabad,delhi': 6,
 'bengaluru,mumbai,pune': 6,
 'delhi ncr,chandigarh': 6,
 'chandigarh,mohali,panchkula': 5,
 'lucknow,noida': 5,
 'chennai,noida': 5,
 'delhi ncr,chennai': 5,
 'delhi ncr (197) ,faridabad,noida,...more': 5,
 'pune (kharadi)': 5,
 'hyderabad (punjagutta)': 5,
 'delhi,noida,gurgaon': 5,
 'pune (pune nashik highway)': 5,
 'mumbai,pune,nagpur': 5,
 'delhi ncr,kolkata': 5,
 'mumbai,pune,bengaluru': 5,
 'mumbai (worli)': 5,
 'bengaluru,hyderabad,mumbai': 5,
 'bengaluru,bengaluru': 5,
 'mumbai suburbs,thane': 5,
 'chennai,bengaluru,hyderabad': 5,
 'pune,chennai': 5,
 'mumbai,bengaluru,chennai,hyderabad,pune,vijayawada,visakhapatnam,coimbatore,kochi': 5,
 'gurgaon,noida,delhi ncr': 5,
 'hyderabad (banjara hills)': 5,
 'hyderabad (kondapur)': 5,
 'delhi ncr, delhi, noida': 5,
 'delhi ncr,bengaluru,noida': 5,
 'delhi ncr,faridabad': 5,
 'delhi ncr,ghaziabad': 5,
 'mumbai (bandra kurla complex)': 5,
 'delhi ncr,delhi,gurgaon,noida': 5,
 'bengaluru (marathahalli)': 5,
 'mumbai,gurgaon': 5,
 'bengaluru (rajaji nagar)': 4,
 'delhi ncr,mumbai,chennai': 4,
 'hyderabad,pune,noida': 4,
 'ghaziabad,delhi': 4,
 'noida (sector-2 noida)': 4,
 'noida (sector-3 noida)': 4,
 'mumbai,bengaluru,gurgaon': 4,
 'mumbai (chembur)': 4,
 'mumbai (mumbai central)': 4,
 'vijayawada,hyderabad': 4,
 'kolkata,bengaluru': 4,
 'mumbai (nariman point)': 4,
 'delhi ncr, noida': 4,
 'delhi ncr,bengaluru,chennai,noida': 4,
 'bengaluru,chennai,hyderabad,pune': 4,
 'gurgaon (sector-24 gurgaon)': 4,
 'karnal,bengaluru': 4,
 'delhi ncr,gurgaon (1) ,...more': 4,
 'delhi,ghaziabad,noida': 4,
 'jodhpur,ahmedabad': 4,
 'delhi ncr,gurgaon,manesar': 4,
 'bengaluru,coimbatore': 4,
 'pune (hadapsar)': 4,
 'bengaluru, chennai, hyderabad, pune, kolkata': 4,
 'bengaluru (electronics city phase 1)': 4,
 'bengaluru (bellandur)': 4,
 'chennai,coimbatore,madurai': 4,
 'bengaluru (hosur road)': 4,
 'mangalore,bengaluru': 4,
 'navi mumbai,mumbai suburbs,mumbai': 4,
 'bengaluru,bengaluru / bangalore,mumbai': 4,
 'delhi ncr, gurgaon': 4,
 'pune,ahmednagar': 4,
 'delhi ncr,mumbai,bengaluru,chennai,hyderabad,pune': 4,
 'delhi ncr,mumbai,kolkata': 4,
 'mumbai,pune,mumbai suburbs': 4,
 'bengaluru (hsr layout)': 4,
 'delhi ncr,mumbai,pune': 4,
 'mumbai,panjim': 4,
 'delhi ncr,bengaluru,gurgaon': 4,
 'mumbai (mindspace)': 4,
 'delhi/ncr(national capital region )': 4,
 'pune,nasik': 4,
 'noida (sector-135 noida)': 4,
 'mumbai suburbs,navi mumbai,thane': 4,
 'pune (yerwada)': 4,
 'noida (sector-16 noida)': 4,
 'chennai,erode,trichy': 4,
 'manesar,gurgaon': 4,
 'pune,nagpur,nasik': 4,
 'jaipur,lucknow,navi mumbai': 4,
 'delhi ncr (janakpuri)': 3,
 'navi mumbai,mumbai,bolpur': 3,
 'mumbai,bengaluru,ahmedabad': 3,
 'bengaluru,chennai,hyderabad,kochi,guntur,rajahmundry,tirupati,vijayawada,visakhapatnam': 3,
 'bengaluru,pune,chennai': 3,
 'delhi,bengaluru': 3,
 'noida,greater noida,ghaziabad': 3,
 'ahmedabad (navrangpura)': 3,
 'pune,maharashtra': 3,
 'kolkata (topsia)': 3,
 'bengaluru (bannerghatta road)': 3,
 'ghaziabad,noida': 3,
 'mumbai,kolkata,lucknow': 3,
 'delhi ncr,delhi,sonepat': 3,
 'ahmedabad,rajkot': 3,
 'nagpur,pune': 3,
 'mumbai,thane,pune': 3,
 'mumbai, thane': 3,
 'bengaluru (wilson garden)': 3,
 'thane,mumbai': 3,
 'hyderabad,vijayawada,visakhapatnam': 3,
 'delhi ncr (nehru place)': 3,
 'delhi ncr,bengaluru,pune': 3,
 'mumbai,delhi ncr': 3,
 'gurgaon,bengaluru,noida': 3,
 'pune (ranjangaon)': 3,
 'kolkata (dalhousie)': 3,
 'bengaluru (domlur)': 3,
 'delhi ncr,mumbai,bengaluru (1) ,chennai,hyderabad,pune,kolkata,ahmedabad,gurgaon,...more': 3,
 'noida (sector-132 noida)': 3,
 'delhi ncr,ghaziabad,greater noida,noida': 3,
 'delhi ncr,gurgaon,delhi': 3,
 'bengaluru,bengaluru / bangalore,delhi': 3,
 'delhi ncr,mumbai,pune,ahmedabad,nagpur,nasik,gujarat,maharashtra': 3,
 'bengaluru (electronic city)': 3,
 'bengaluru, chennai, hyderabad, pune': 3,
 'chandigarh,indore,jaipur': 3,
 'mumbai suburbs,navi mumbai,mumbai': 3,
 'mumbai (govandi)': 3,
 'bengaluru (btm layout)': 3,
 'kochi,bengaluru': 3,
 'ahmedabad (bodakdev)': 3,
 'bengaluru,mangalore': 3,
 'noida (sector-58 noida)': 3,
 'hyderabad, ap': 3,
 'ahmedabad,pune': 3,
 'noida (sector-10 noida)': 3,
 'manesar,gurgaon,haryana': 3,
 'gurgaon,delhi ncr,delhi': 3,
 'ahmedabad,gandhinagar,vadodara': 3,
 'bengaluru,karnataka': 3,
 'gurgaon,noida,delhi': 3,
 'chennai,trivandrum': 3,
 'bengaluru,vadodara': 3,
 'noida (sector-142 noida)': 3,
 'mumbai (mulund)': 3,
 'delhi,pune,mumbai': 3,
 'mumbai,navi mumbai,pune': 3,
 'pune,delhi': 3,
 'bengaluru,kolkata,ahmedabad': 3,
 'chennai,gurgaon': 3,
 'bengaluru,karnal': 3,
 'hyderabad, andhra pradesh, india': 3,
 'mumbai,malda': 3,
 'gandhinagar,ahmedabad,gujarat': 3,
 'kolkata,bhubaneshwar,guwahati': 3,
 'hyderabad, andhra pradesh': 3,
 'mumbai,maharashtra': 3,
 'mumbai,bengaluru,chennai,hyderabad,pune,kolkata,ahmedabad,bhubaneshwar,bellary': 3,
 'bengaluru (5th block koramangala)': 3,
 'noida (sector-127 noida)': 3,
 'navi mumbai,thane,mumbai': 3,
 'delhi ncr,mumbai,hyderabad': 3,
 'mumbai (dn nagar)': 3,
 'hyderabad,bengaluru,mumbai': 3,
 'mumbai,chennai,delhi': 3,
 'hyderabad,pune,kolkata': 3,
 'delhi ncr,hyderabad': 3,
 'chandigarh,noida': 3,
 'noida,other city': 3,
 'mumbai,pune,mumbai,pune': 3,
 'chennai,qatar': 3,
 'noida (sector-64 noida)': 3,
 'bengaluru,chennai,kochi': 3,
 'bengaluru,chennai,coimbatore': 3,
 'pune (koregaon park)': 3,
 'ahmedabad,rajkot,surat': 3,
 'banur,pune': 3,
 'mumbai,ahmedabad,vadodara': 3,
 'gurgaon,hyderabad': 3,
 'ahmedabad,bengaluru': 3,
 'delhi ncr (197) ,gurgaon,noida,...more': 3,
 'navi mumbai,thane': 3,
 'chandigarh,delhi': 3,
 'bengaluru (sector 6 hsr layout)': 3,
 'gandhinagar,ahmedabad': 3,
 'bengaluru,mumbai,chennai': 3,
 'hyderabad,bengaluru,mumbai,pune,chennai': 3,
 'chennai,coimbatore,trichy': 3,
 'chennai,hyderabad,trichy': 3,
 'hyderabad (jubilee hills)': 3,
 'mumbai (sector 1 ghansoli) ,navi mumbai': 3,
 'hyderabad,gurgaon': 3,
 'pune,jaipur': 3,
 'noida,bengaluru': 3,
 'delhi ncr,faridabad,ghaziabad': 3,
 'ahmedabad (makarba)': 2,
 'hyderabad (begumpet)': 2,
 'delhi ncr (sector-63 noida)': 2,
 'bengaluru (3rd phase jp nagar)': 2,
 'mumbai (mahakali nagar)': 2,
 'chennai,hyderabad,bengaluru': 2,
 'dehradun,delhi ncr': 2,
 'delhi ncr,jaipur': 2,
 'chennai,japan': 2,
 'hyderabad (lb nagar)': 2,
 'kolkata (brabourne road)': 2,
 'bengaluru,pune,ahmedabad': 2,
 'jaipur,ahmedabad': 2,
 'chennai, bengaluru': 2,
 'chandigarh,haryana': 2,
 'ahmedabad (science city)': 2,
 'chennai,erode,karur': 2,
 'delhi ncr,lucknow': 2,
 'faridabad,gurgaon,delhi': 2,
 'pune (baner pashan link road)': 2,
 'mumbai,vadodara': 2,
 'chennai,coimbatore,erode': 2,
 'bengaluru,delhi ncr,gurgaon': 2,
 'mumbai (powai) ,mumbai suburbs': 2,
 'jaipur,chennai': 2,
 'delhi (naraina)': 2,
 'hyderabad (ameerpet)': 2,
 'mohali,chandigarh,panchkula': 2,
 'gurgaon,manesar,haryana': 2,
 'bengaluru (hal 2nd stage)': 2,
 'pune,kolkata,ahmedabad': 2,
 'delhi (rohini)': 2,
 'delhi ncr,mumbai,mumbai suburbs': 2,
 'ghaziabad,noida (1) ,...more': 2,
 'pune,banur': 2,
 'faridabad,chandigarh,haryana': 2,
 'delhi ncr,delhi,noida,gurgaon': 2,
 'greater noida,noida,ghaziabad': 2,
 'mumbai, pune, ahmedabad': 2,
 'mumbai,chennai,pune': 2,
 'delhi ncr,greater noida,meerut': 2,
 'delhi,pune,hyderabad,bengaluru,mumbai': 2,
 'mumbai,hyderabad,pune': 2,
 'delhi ncr (saket)': 2,
 'noida,bengaluru,hyderabad': 2,
 'ahmedabad,surat,rajkot': 2,
 'delhi (janakpuri)': 2,
 'faridabad,gurgaon': 2,
 'chennai,hyderabad,trivandrum': 2,
 'bengaluru,delhi ncr,mumbai': 2,
 'bengaluru,chennai,delhi': 2,
 'mumbai (chakala)': 2,
 'pune, hyderabad, bengaluru': 2,
 'delhi ncr, gurgaon, noida': 2,
 'bengaluru (panathur, marathahalli)': 2,
 'delhi ncr,hyderabad,pune': 2,
 'kolkata,guwahati': 2,
 'delhi,kolkata': 2,
 'delhi ncr,delhi,faridabad': 2,
 'howrah': 2,
 'bawal,gurgaon': 2,
 'delhi (saket)': 2,
 'kolkata,kolkata,mumbai,bangalore,ahmedabad,jamshedpur': 2,
 'mumbai,bengaluru,gaya,mumbai suburbs,navi mumbai,patna': 2,
 'hyderabad,madhepura': 2,
 'bengaluru, chennai, hyderabad': 2,
 'kolkata,mumbai': 2,
 'kolkata,bhubaneshwar': 2,
 'mumbai (shanti nagar borivali)': 2,
 'faridabad,haryana': 2,
 'mumbai (airoli)': 2,
 'pune (sector no-7 bhosari)': 2,
 'ahmedabad,vadodara,bhopal,chennai,lucknow': 2,
 'ahmedabad (vatva)': 2,
 'chennai, noida': 2,
 'noida,bengaluru,chennai': 2,
 'delhi (okhla)': 2,
 'noida (phase-ii)': 2,
 'mumbai (rajendra nagar)': 2,
 'mumbai,vasai': 2,
 'delhi ncr,chennai,bengaluru': 2,
 'noida (sector-125 noida)': 2,
 'agra,ahmedabad,allahabad': 2,
 'delhi ncr (pocket-2 sector 6 dwarka)': 2,
 'tirupati,trivandrum,ahmedabad': 2,
 'hyderabad (sd road)': 2,
 'noida,hyderabad,bengaluru': 2,
 'delhi ncr, chandigarh, mohali': 2,
 'bengaluru,kolkata,delhi': 2,
 'pune,indore': 2,
 'bengaluru,hyderabad,ahmedabad': 2,
 'delhi ncr,mumbai,bengaluru,chennai,hyderabad,pune,vijayawada,visakhapatnam,united states (u.s)': 2,
 'chennai,gurgaon,bengaluru': 2,
 'mumbai,thane,navi mumbai': 2,
 'hyderabad,bengaluru,pune,chennai': 2,
 'chennai,delhi,mumbai': 2,
 'bengaluru (malleshwaram)': 2,
 'mumbai,pune,delhi ncr': 2,
 'bengaluru,chennai,hyderabad,pune,nagpur': 2,
 'hyderabad (srinagar colony)': 2,
 'panchkula,mohali,chandigarh': 2,
 'hyderabad (tellapur)': 2,
 'pune,gujarat': 2,
 'jodhpur,jaipur,ahmedabad': 2,
 'delhi ncr,mumbai,bengaluru,chennai,hyderabad,pune,kolkata,ahmedabad,delhi': 2,
 'mumbai,nagpur,pune,kota,delhi': 2,
 'mumbai,purulia': 2,
 'chennai,delhi ncr': 2,
 'mumbai, mumbai suburbs, navi mumbai': 2,
 'bengaluru (ulsoor)': 2,
 'kolkata,noida': 2,
 'mumbai,bengaluru,pune,kolkata,ahmedabad,agartala': 2,
 'bengaluru,hyderabad,kolkata': 2,
 'delhi,nagpur,mumbai,kota,pune': 2,
 'kolkata,visakhapatnam,gurgaon': 2,
 'delhi ncr,meerut,sonepat': 2,
 'delhi ncr,pune,noida': 2,
 'pune (pirangut)': 2,
 'nasik,pune': 2,
 'mumbai,pune,delhi': 2,
 'chennai,kolkata': 2,
 'mumbai,nagpur': 2,
 'delhi ncr (rohini)': 2,
 'chennai,dubai/ uae': 2,
 'bengaluru,hosur,mysore': 2,
 'mumbai (seepz)': 2,
 'delhi (malviya nagar)': 2,
 'hyderabad,andra': 2,
 'bengaluru (palace road)': 2,
 'ambala,gurgaon': 2,
 'mumbai,pune,noida': 2,
 'mumbai,chennai,bengaluru': 2,
 'bengaluru,varanasi / banaras': 2,
 'ahmedabad (gota)': 2,
 'delhi ncr,delhi,faridabad,ghaziabad,gurgaon,noida': 2,
 'bengaluru,chennai,mumbai': 2,
 'delhi,gurgaon,ghaziabad': 2,
 'hyderabad,chennai,mumbai': 2,
 'nagpur,nasik,noida': 2,
 'new delhi': 2,
 'mumbai,bengaluru,delhi ncr': 2,
 'mumbai (prabhadevi)': 2,
 'bengaluru,delhi,pune': 2,
 'bengaluru,hubli': 2,
 'hyderabad,mumbai,delhi': 2,
 'hyderabad,pune,ahmedabad': 2,
 'kolkata,barasat': 2,
 'coimbatore,chennai': 2,
 'chennai,mumbai,delhi': 2,
 'ahmedabad (vastrapur)': 2,
 'vapi,valsad,vadodara,surat,jamnagar,daman & diu,dadra and nagar haveli,bharuch,ahmedabad': 2,
 'delhi,haryana': 2,
 'delhi ncr (sector-24 gurgaon) ,gurgaon,noida': 2,
 'coimbatore,bengaluru': 2,
 'hyderabad,bengaluru,mumbai,chennai,delhi': 2,
 'ghaziabad,noida,delhi': 2,
 'hyderabad,kolkata': 2,
 'ahmedabad,surat': 2,
 'chandigarh,coimbatore,cuttack,kochi,guwahati,hubli,jamshedpur,mangalore,mysore': 2,
 'ghaziabad (vaishali)': 2,
 'hyderabad,noida': 2,
 'mumbai (mazgaon)': 2,
 'bengaluru (bommenahalli)': 2,
 'mumbai,chennai,kolkata,delhi': 2,
 'bengaluru,gurgaon,noida': 2,
 'srinagar,bengaluru,kolkata': 2,
 'delhi,kanpur': 2,
 'delhi,delhi ncr,noida': 2,
 'delhi ncr,delhi,faridabad,noida': 2,
 'pune (marunji)': 2,
 'bengaluru,chennai,noida': 2,
 'mumbai (ambernath)': 2,
 'hyderabad,bengaluru,chennai,pune': 2,
 'hubli,mysore,faridabad,mumbai': 2,
 'delhi ncr,bengaluru,chennai,hyderabad,pune': 2,
 'bengaluru (kudlu)': 2,
 'delhi ncr,mumbai,bengaluru,chennai,hyderabad,pune,kolkata,ahmedabad,chandigarh': 2,
 'pune (shirwal)': 2,
 'pune,nagpur,raipur': 2,
 'delhi ncr, delhi': 2,
 'bengaluru, chennai': 2,
 'delhi ncr,bengaluru,saudi arabia': 2,
 'mumbai (lokhandwala)': 2,
 'bengaluru,ahmedabad,bengaluru / bangalore,chennai,delhi,pune': 2,
 'noida, gurgaon': 2,
 'ahmedabad,jodhpur': 2,
 'chennai,madurai,vellore': 2,
 'hyderabad,india': 2,
 'delhi ncr,vadodara': 2,
 'noida,gurgaon,delhi': 2,
 'bengaluru,chennai,hyderabad,pune,bhubaneshwar': 2,
 'delhi,lucknow': 2,
 'delhi ncr,noida (1) ,...more': 2,
 'thane,navi mumbai': 2,
 'chennai,madurai,salem': 2,
 'bengaluru,ahmedabad': 2,
 'mumbai,pune,ahmedabad,vadodara': 2,
 'mohali,pune': 2,
 'navi mumbai,mumbai suburbs': 2,
 'nagpur,mumbai': 2,
 'noida (sector-5 noida)': 2,
 'chennai,coimbatore,salem': 2,
 'pune (chinchwad)': 2,
 'ahmedabad,chennai,delhi': 2,
 'bengaluru (cunningham road)': 2,
 'bengaluru,kolkata,ahmedabad,delhi,mumbai suburbs,mumbai': 2,
 'noida,delhi,noida/greater noida': 2,
 'hyderabad,bhubaneshwar': 2,
 'ahmedabad,vadodara,rajkot': 2,
 'bengaluru,hyderabad,kochi': 2,
 'mumbai,bengaluru,chennai,hyderabad,navi mumbai,vasco da gama,vellore,visakhapatnam,warangal': 2,
 'delhi ncr,delhi,greater noida,gurgaon,noida': 2,
 'bengaluru (vasanth nagar)': 2,
 'delhi ncr (lado sarai)': 2,
 'mumbai (sakinaka)': 2,
 'delhi ncr,mumbai,kochi': 2,
 'mumbai,gurgaon,delhi': 2,
 'pune,noida': 2,
 'delhi ncr,bhiwadi': 2,
 'bengaluru (panathur)': 2,
 'gurgaon,australia': 2,
 'pune (akurdi)': 2,
 'chennai,trichy,vellore': 2,
 'ghaziabad,greater noida,noida': 2,
 'noida (sector-59 noida)': 2,
 'greater noida (kasna)': 2,
 'bengaluru (budigere)': 2,
 'kalu,thane,vashi': 2,
 'kolkata (new town)': 2,
 'hyderabad,chennai,bengaluru': 2,
 'hyderabad,bengaluru,chennai,kolkata': 2,
 'noida (sector-126 noida)': 2,
 'bengaluru (basavangudi)': 2,
 'rohtak,gurgaon,ghaziabad,bhiwani': 2,
 'pune (senapati bapat road)': 2,
 'delhi,chandigarh': 2,
 'gurgaon,jaipur': 2,
 'chandigarh,ludhiana,jalandhar': 2,
 'mumbai,delhi,kochi,kolkata,navi mumbai,guwahati,panjim': 2,
 'hyderabad,itanagar,patna,raipur,panjim,gandhinagar,chandigarh,shimla,srinagar': 2,
 'mumbai,noida': 2,
 'chennai,pune,kolkata,ahmedabad,coimbatore,delhi,gurgaon,mysore': 2,
 'chennai,salem,trivandrum': 2,
 'navi mumbai,vashi': 2,
 'mumbai,pune,indore': 2,
 'aurangabad,pune': 2,
 'pune,raigad': 2,
 'gurgaon (c block sushant lok phase - i)': 2,
 'pune,kolkata': 2,
 'delhi ncr (safdarjung enclave)': 2,
 'chennai,erode,madurai': 2,
 'bengaluru (jalahalli)': 2,
 'gurgaon,chennai': 2,
 'ahmedabad,vadodara,panipat,baddi,guwahati': 2,
 'mumbai,mumbai suburbs,navi mumbai,thane,vasai': 2,
 'delhi ncr,mumbai,bengaluru,hyderabad,pune': 2,
 'ahmedabad,gujarat,india': 2,
 'kanpur,delhi': 2,
 'delhi (greater kailash)': 2,
 'delhi ncr (sector-18a dwarka)': 2,
 'surat,pune': 2,
 'chennai,kochi': 2,
 'delhi ncr,bengaluru,chennai,hyderabad': 2,
 'ahmedabad,anand': 2,
 'hyderabad,bengaluru,mumbai,delhi ncr': 2,
 'bengaluru,hyderabad,gurgaon': 2,
 'chennai tirchy,kumbakonam salem,coimbatore madurai': 2,
 'hyderabad,mumbai,pune': 2,
 'bangalore': 2,
 'delhi,gurgaon (1) ,...more': 2,
 'bengaluru,mumbai,hyderabad': 2,
 'thane,mumbai,navi mumbai': 2,
 'bengaluru,trivandrum': 2,
 'delhi ncr,kolkata,chandigarh': 2,
 'delhi ncr,delhi (1) ,...more': 2,
 'pune,solapur': 2,
 'pune (pimpri)': 2,
 'hyderabad,gurgaon,coimbatore': 2,
 'pune (wakad)': 2,
 'delhi (connaught place)': 2,
 'noida,gurgaon,delhi ncr': 2,
 'hyderabad,ahmedabad,bengaluru,mumbai,pune,chennai,kolkata,delhi': 2,
 'pune,pune,chennai,mumbai': 1,
 'bengaluru (sector 5 hsr layout)': 1,
 'mumbai,vadodara,pune,bengaluru': 1,
 'hyderabad (miyapur)': 1,
 'delhi ncr,raipur,lucknow': 1,
 'chennai,kannur,palakkad': 1,

### Recommendation Logic

In [249]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [250]:
df.columns

Index(['Uniq Id', 'Crawl Timestamp', 'Job Title', 'Job Salary',
       'Job Experience Required', 'Key Skills', 'Role Category', 'Location',
       'Functional Area', 'Industry', 'Role', 'Skill_1', 'Skill_2', 'Skill_3',
       'Job_Exp_Min', 'Job_Exp_Max'],
      dtype='object')

In [251]:
def combined_features(row):
    return row['Role Category']+" "+row['Location']+" "+row['Industry']+" "+row['Skill_1']+" "+row['Skill_2']+" "+row['Skill_3']

df["combined_features"] = df.apply(combined_features, axis =1)

In [252]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df["combined_features"])
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [253]:
cosine_sim = cosine_similarity(count_matrix)

In [263]:
job_searched = "python"
def get_index_from_title(title):
    return df[df["Skill_1"] == title].index.values[0]
job_index = get_index_from_title(job_searched)

In [264]:
job_index

156

In [265]:
similar_jobs = list(enumerate(cosine_sim[job_index]))
sorted_similar_jobs = sorted(similar_jobs, key=lambda x:x[1], reverse=True)

In [266]:
def get_title_from_index(index):
    return df[df.index == index]["Skill_1"].values[0]
i=0
for job in sorted_similar_jobs:
    print(get_title_from_index(job[0]))
    i=i+1
    if i>5:
        break

python
analyst
android
python
Not Given
Not Given

In [258]:
df[df['Job Title']=='python developer'].head()

,Uniq Id,Crawl Timestamp,Job Title,Job Salary,Job Experience Required,Key Skills,Role Category,Location,Functional Area,Industry,Role,Skill_1,Skill_2,Skill_3,Job_Exp_Min,Job_Exp_Max,combined_features
156,694fa3ab36d8ac71cb7d9f518aff1df0,2019-08-06 02:44:20 +0000,python developer,Not Disclosed by Recruiter,1 - 3 yrs,Python,programming & design,chennai,"IT Software - Application Programming , Mainte...",recruitment,Software Developer,python,Not Given,Not Given,1,3,programming & design chennai recruitment pytho...
217,2ed64715e1d1fd3bd0d8e6bc32327bf2,2019-08-05 09:33:26 +0000,python developer,Not Disclosed by Recruiter,0 - 1 yrs,Debugging| Troubleshooting| Python| Interpers...,programming & design,gurgaon,"IT Software - Application Programming , Mainte...",it-software,Software Developer,debugging,troubleshooting,python,0,1,programming & design gurgaon it-software debug...
1057,dcff7afd271a2de8eee3718dd3a83c30,2019-08-05 09:21:15 +0000,python developer,Not Disclosed by Recruiter,1 - 5 yrs,SQL| Javascript| Python| rest| development| g...,programming & design,hyderabad,"IT Software - Application Programming , Mainte...",it-software,Software Developer,sql,javascript,python,1,5,programming & design hyderabad it-software sql...
1568,2604e11d4ae863951b1a567ded2fa356,2019-07-06 15:54:17 +0000,python developer,"4,00,000 - 8,00,000 PA.",2 - 6 yrs,Not given,programming & design,bengaluru,"IT Software - Application Programming , Mainte...",it-software,Software Developer,Not Given,Not Given,Not Given,2,6,programming & design bengaluru it-software Not...
1706,1367178f55f56a3d306c78e3a9fd3702,2019-08-04 22:30:04 +0000,python developer,Not Disclosed by Recruiter,0 - 3 yrs,Data Science| Data Analytics| Python,programming & design,hyderabad,"IT Software - Application Programming , Mainte...",it-software,Software Developer,data science,data analytics,python,0,3,programming & design hyderabad it-software dat...